name: DnD-creator
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.14
  - attr=2.5.2
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - cairo=1.18.4
  - cyrus-sasl=2.1.28
  - dbus=1.16.2
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.14.1
  - gettext=0.25.1
  - gettext-tools=0.25.1
  - glib=2.86.2
  - glib-tools=2.86.2
  - graphite2=1.3.14
  - gst-plugins-base=1.24.11
  - gstreamer=1.24.11
  - harfbuzz=12.2.0
  - icu=75.1
  - keyutils=1.6.3
  - krb5=1.21.3
  - lame=3.100
  - ld_impl_linux-64=2.45
  - libasprintf=0.25.1
  - libasprintf-devel=0.25.1
  - libcap=2.77
  - libclang-cpp21.1=21.1.7
  - libclang13=21.1.7
  - libcups=2.3.3
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libevent=2.1.12
  - libexpat=2.7.3
  - libffi=3.5.2
  - libflac=1.4.3
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgettextpo=0.25.1
  - libgettextpo-devel=0.25.1
  - libgl=1.7.0
  - libglib=2.86.2
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.2.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - libllvm21=21.1.7
  - liblzma=5.8.1
  - libnsl=2.0.1
  - libntlm=1.8
  - libogg=1.3.5
  - libopengl=1.7.0
  - libopus=1.5.2
  - libpciaccess=0.18
  - libpng=1.6.51
  - libpq=18.1
  - libsndfile=1.2.2
  - libsqlite=3.51.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libsystemd0=258.2
  - libuuid=2.41.2
  - libvorbis=1.3.7
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.13.1
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libzlib=1.3.1
  - mpg123=1.32.9
  - ncurses=6.5
  - nspr=4.38
  - nss=3.118
  - openldap=2.6.10
  - openssl=3.6.0
  - packaging=25.0
  - pcre2=10.47
  - pdfrw=0.4
  - pip=25.3
  - pixman=0.46.4
  - ply=3.11
  - pthread-stubs=0.4
  - pulseaudio-client=17.0
  - pyqt=5.15.11
  - pyqt5-sip=12.17.0
  - python=3.12.12
  - python_abi=3.12
  - qt-main=5.15.15
  - readline=8.2
  - setuptools=80.9.0
  - sip=6.10.0
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.3.0
  - tzdata=2025b
  - wheel=0.45.1
  - xcb-util=0.4.1
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.46
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.2
  - xorg-libxrender=0.9.12
  - xorg-libxshmfence=1.3.3
  - xorg-libxxf86vm=1.1.6
  - zstd=1.5.7
prefix: /home/dardu/anaconda3/envs/DnD-creator
